export const colors = {
  SCREEN_BACKGROUND: '#1a1a1a',
  FONT_COLOR: 'white',
  PRIMARY_FONT_COLOR: '#000000',
  SECONDARY_FONT_COLOR: '#868AA5',
  BUTTON_PRIMARY_BACKGROUND: '#000000',
  BUTTON_SECONDARY_BACKGROUND: '#FFFFFF',
  SHADOW_COLOR: '#333333',
  LOGO_BACKGROUND: '#FFFF13',
  BORDER_COLOR: '#E1E3EB',
  PLACEHOLDER_COLOR: '#CFD1DC',
  INPUT_TEXT_COLOR: '#717289',
  BOTTOM_SHEET_BACKGROUND: '#FFFFFF',
};
